// Autonomy Layer Type Definitions
// Generated by Scaffold Agent for Polywave (autonomy-web-ui)
// These types mirror the backend autonomy layer (v0.58.0) from polywave-go

// Autonomy level type — mirrors pkg/autonomy.Level
export type AutonomyLevel = 'gated' | 'supervised' | 'autonomous'

// Autonomy config — mirrors pkg/autonomy.Config
export interface AutonomyConfig {
  level: AutonomyLevel
  max_auto_retries: number
  max_queue_depth: number
}

// Queue item — mirrors pkg/queue.Item
export interface QueueItem {
  title: string
  priority: number
  depends_on?: string[]
  feature_description: string
  status: 'queued' | 'in_progress' | 'complete' | 'blocked'
  autonomy_override?: string
  require_review?: boolean
  slug?: string
  file_path?: string
}

// Daemon state — mirrors pkg/engine.DaemonState
export interface DaemonState {
  running: boolean
  current_impl?: string
  current_wave?: number
  queue_depth: number
  completed_count: number
  blocked_count: number
}

// Shared base for any IMPL reference in the UI.
// Extended by PipelineEntry (pipeline view) and ImplTierStatus (program board).
export interface ImplReference {
  slug: string
  title: string
  status: string
}

// Pipeline entry — combined view of completed + executing + queued
export interface PipelineEntry extends ImplReference {
  // slug, title, status inherited from ImplReference
  repo?: string                    // repo name from polywave.config.json
  wave_progress?: string           // e.g. "Wave 2/3"
  active_agent?: string            // e.g. "Agent B"
  blocked_reason?: string
  queue_position?: number
  depends_on?: string[]
  completed_at?: string
  elapsed_seconds?: number
  program_slug?: string            // parent PROGRAM slug, if this IMPL belongs to a program
  program_title?: string           // parent PROGRAM title
  program_tier?: number            // tier number within parent program (U2)
  program_tiers_total?: number     // total tiers in parent program (U2)
}

// Pipeline response from GET /api/pipeline
export interface PipelineResponse {
  entries: PipelineEntry[]
  metrics: PipelineMetrics
  autonomy_level: AutonomyLevel
}

// Throughput metrics
export interface PipelineMetrics {
  impls_per_hour: number
  avg_wave_seconds: number
  queue_depth: number
  blocked_count: number
  completed_count: number
}

// Add queue item request
export interface AddQueueItemRequest {
  title: string
  priority: number
  feature_description: string
  depends_on?: string[]
  autonomy_override?: string
  require_review?: boolean
}
